train:
  num_samples: 1000
  batch_size: 128
  num_workers: null # null means number of cpus will be used
val:
  num_samples: 1000
  batch_size: 256
  num_workers: null  # null means number of cpus will be used