model:
  _target_: cocoa_mapping.models.kalitschek.KalitschekModel
  include_height: false
  in_channels: 12
preprocessor:
  _target_: cocoa_mapping.models.kalitschek.KalitschekPreprocessor
  channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]